[build]
  publish = "automation-coca/public"
  functions = "functions"

[[redirects]]
from = "/api/tiendas"
to = "/.netlify/functions/tiendas-api"
status = 200

[[redirects]]
from = "/api/tiendas/:id"
to = "/.netlify/functions/tiendas-api"
status = 200
